### ISSUE TITLE
Support for Composite primary keys

### ISSUE THREAD

**Issue by pikou** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#3]
Hello I am loving your library , thank you very much for creating it .
This is a question rather that an issue as I want to know if there is support for composite primary keys in the Repository. I am having some trouble understanding this as
`IRepository<TEntity, TPk>` seems to ahve one key unless I am missing something very obvious.

Thanks again

**Comment by generik0** [comment]
Hi @Pikou. Thanks for that :-)
Yes I made the repository only to support 1 primary key. But I use FastCRUD with dapper that does support composite key.
So the Get method will support it.
Otherwise you can do overrights in your implementation and use e.g. Session.Find etc from FastCRUD and it should work with composite.

The actual reason I based my library to utilize FastCRUD was because it's methods supported more than just the key. 

In actual fact the TPk is only used for GetKey and SaveOrUpdate. So just override what you need :-)

**Comment by pikou** [comment]
Hello generik0

Thanks for your very fast reply :)
